version: '3.1'

services:

  drupal:
    image: drupal:8-apache
    network_mode: host
    ports:
      - 8080:80
    volumes:
     - ./modules:/var/www/html/modules
     - ./profiles:/var/www/html/profiles
     - ./themes:/var/www/html/themes
     - ./sites:/var/www/html/sites
    restart: always